#!/usr/bin/env php
<?php

require __DIR__.'/../../autoload.php';

$app = new Symfony\Component\Console\Application('Laravel Envoy', '1.0.17');
$app->add(new Laravel\Envoy\Console\RunCommand);
$app->add(new Laravel\Envoy\Console\SshCommand);
$app->add(new Laravel\Envoy\Console\InitCommand);

$app->run();
